### ISSUE TITLE
当图片元素很多时，清除效果感觉不是很好啊

### ISSUE THREAD

**Issue by ysh199882** [shifu-group/inpaint_wechat#1]

**Comment by wangqmshf** [comment]
有可能  选择小区域试试。麻烦你发个截图出来，可能和模型有关系

**Comment by davidshen111** [comment]
1. 可以多尝试几次，涂抹区域不一样会有不一样的结果。
2. 使用到AI模型是蒸馏以后的版本，只有不到30M，运行在手机上。对于复杂图片的话，最好多次消除，累积调整。
